## Testing ArmPSM

In [1]:
from ArmPSM_model import ArmPSM

In [1]:
from pyrep.pyrep import PyRep

In [2]:
import numpy as np

In [4]:
pr = PyRep()
pr.launch('/home/arclab-flo/Desktop/Bose/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/scenes/single_arm_one_marker.ttt')

In [5]:
psm = ArmPSM(pr, 1)

In [6]:
pr.start()

In [7]:
jointAngles, jawAngle = psm.getJointAngles()

In [8]:
jointAngles, jawAngle

(array([0.       , 0.       , 0.1      , 0.       , 0.       , 0.0869971]),
 0.21319000454561912)

In [9]:
jointAngles[1] = 0
jointAngles[2] = 0.15
jawAngle += 0

In [10]:
psm.setJointAngles(jointAngles, jawAngle)
pr.step()

In [13]:
psm.getJointAngles()

(array([ 3.28411255e-03,  6.74923431e-05,  5.75868413e-02, -3.88734430e-01,
         4.05890085e-02,  2.47310172e-03]), -0.0005314163809222124)

In [14]:
pr.stop()

In [15]:
pr.shutdown()

## Testing ArmECM

In [3]:
from ArmECM_model import ArmECM

In [4]:
pr = PyRep()
pr.launch('/home/arclab-flo/Desktop/Bose/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/scenes/single_arm_one_marker.ttt')

In [5]:
ecm = ArmECM()

In [7]:
jointAngles = ecm.getJointAngles()

In [8]:
jointAngles

array([0.       , 0.2617994, 0.       , 0.       ])

In [9]:
pr.start()

In [10]:
jointAngles[2] = 0.1
ecm.setJointAngles(jointAngles)

In [11]:
ecm.getJointAngles()

array([0.       , 0.2617994, 0.1      , 0.       ])

In [12]:
pr.step()

In [13]:
pr.stop()
pr.shutdown()