In [1]:
import gym
import time
import numpy as np
import ECM_dVRL_v01
import numdifftools as nd

In [2]:
env = gym.make('ECM-v0')

In [3]:
env.reset()

{'observation': array([-1.,  0.,  0.,  0.]),
 'achieved_goal': array([-3.81349477e-02,  5.85906482e-04,  8.07932473e-01,  1.00000000e+00]),
 'desired_goal': array([0., 0., 0., 1.])}

In [4]:
env.get_achieved_goal()

array([-3.81349477e-02,  5.85906482e-04,  8.07932473e-01,  1.00000000e+00])

In [5]:
env.ecm.getTestGoalPosition()

array([-0.00928831, -0.00829995, -0.7494424 ])

In [6]:
theta = env.ecm.getJointAngles()
lr = 1e-4
theta_new = 0.
tolerance = 1e-3
max_iter = 100
iterations = 0
while True:
    x_diff = env.get_achieved_goal()[:-1] - env.desired_goal[:-1]
    J = env.ecm.getJacobian().T
    theta_new = lr * np.dot(np.linalg.pinv(J), x_diff) + theta
    if np.linalg.norm(theta - theta_new) < tolerance:
        print (env.get_achieved_goal()[:-1], env.desired_goal[:-1], iterations)
        break
    else:
        print (env.get_achieved_goal()[:-1], theta, theta_new)
        env.ecm.setJointAngles(theta_new)
    theta = theta_new
    iterations += 1
    time.sleep(1.0)

[-3.81349477e-02  5.85906482e-04  8.07932473e-01] [-1.  0.  0.  0.] [-9.98601760e-01 -1.08082723e-04  6.16400267e-04 -3.55710986e-03]
[-3.81348301e-02  5.85806346e-04  8.07933079e-01] [-9.98601760e-01 -1.08082723e-04  6.16400267e-04 -3.55710986e-03] [-9.97205209e-01 -2.15976035e-04  1.23508288e-03 -7.10471531e-03]
[-3.81346469e-02  5.85968353e-04  8.07933046e-01] [-9.97205209e-01 -2.15976035e-04  1.23508288e-03 -7.10471531e-03] [-9.95810370e-01 -3.23681410e-04  1.85605286e-03 -1.06428539e-02]
[-3.81350463e-02  5.85505500e-04  8.07932745e-01] [-9.95810370e-01 -3.23681410e-04  1.85605286e-03 -1.06428539e-02] [-9.94417226e-01 -4.31201339e-04  2.47929112e-03 -1.41716383e-02]
[-3.81351153e-02  5.85884696e-04  8.07932845e-01] [-9.94417226e-01 -4.31201339e-04  2.47929112e-03 -1.41716383e-02] [-9.93025791e-01 -5.38533990e-04  3.10478958e-03 -1.76909692e-02]
[-3.81348547e-02  5.86433662e-04  8.07932828e-01] [-9.93025791e-01 -5.38533990e-04  3.10478958e-03 -1.76909692e-02] [-9.91636034e-01 -6.45

KeyboardInterrupt: 

In [7]:
env.close()

In [8]:
np.radians(-75), np.radians(-50)

(-1.3089969389957472, -0.8726646259971648)

In [8]:
np.degrees(-1.0)

-57.29577951308232