In [1]:
from pyrep.pyrep import PyRep
from ArmPSM_model import ArmPSM
from ArmECM_model import ArmECM
import numpy as np

In [2]:
pr = PyRep()
pr.launch('/home/arclab-flo/Desktop/Bose/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/scenes/single_arm.ttt')
pr.start()

In [3]:
ecm = ArmECM()

In [4]:
psm = ArmPSM()

In [5]:
ecm.getCurrentPose()

[0.021577417850494385,
 -0.017796635627746582,
 -0.7434645295143127,
 0.03515362739562988,
 0.5946381688117981,
 -0.802949070930481,
 -0.021037936210632324]

In [6]:
psm.getPoseAtEE()

(array([-1.54972076e-06, -4.29153442e-06, -1.09997630e-01]),
 array([-0.69626409, -0.1226594 ,  0.12273826,  0.69649577]))

In [7]:
np.r_[psm.getPoseAtEE()]

array([-1.54972076e-06, -4.29153442e-06, -1.09997630e-01, -6.96264088e-01,
       -1.22659400e-01,  1.22738257e-01,  6.96495771e-01])

In [8]:
pr.stop()
pr.shutdown()